### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by NahuelMartinez18** [KevinDQuintana/mercadoliebre#1]
- No está el texto que dice "Comprá en cuotas y sin tarjeta de crédito".
- No funciona el botón de login desde la página de register y si toco el botón de register desde la página de register me lleva al login.  
- En la página de register en footer no está centrado y en la página de login no hay footer.   
- En la página de register no está el texto del copyright. 

- Me gustó mucho el diseño de la página, se ve moderno y mas fiel a la página original de mercado libre.
- Creo que el diseño de los bordes de la barra de búsqueda debería ser de otro color porque el verde desentona un poco con el estilo de la página.

**Comment by KevinDQuintana** [comment]
- Agregado el texto de "Comprá en cuotas y sin tarjeta de crédito".
- Ya funciona el boton de login desde todas las vistas.
- Ahora el footer esta centrado y tambien se puede visualizar en todas las vistas.
- El texto de copyright ahora aparece en todas las vistas.
- El borde verde de la barra de busqueda servia para hacer debugging, no deberia haberse subido, pero ya esta corregido.
